### ISSUE TITLE
Is there any chance to make this running on Windows?

### ISSUE THREAD

**Issue by Xotabu4** [roguephysicist/q3a-server#1]
Hi! 

Thanks for the project!
Is there any way to run this on Windows?

**Comment by roguephysicist** [comment]
Hey,

[Ioquake3](https://ioquake3.org/get-it/) is available for windows, so I don't see any reason why it wouldn't work. You can even use the same .cfg files that I have provided here.

You will only need to figure out how to run the server executable (probably from the command line) and then supply it with the appropriate command in order to read the .cfg files. Let me know if it works!

**Comment by roguephysicist** [comment]
Did you get it to work?

**Comment by Xotabu4** [comment]
Didn't tried yet. Will test this soon!
